### ISSUE TITLE
This is pretty nice! 

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify_graphql#22]
I have been wildly all over the place with Shopify and GraphQL in the last few years. 

Spending just 30 minutes with this little library and it works well! Congratulations! I hope I can contribute to it in some meaningful way.

**Comment by kirillplatonov** [comment]
Thanks! That gem is not that popular but pretty useful when dealing with Shopify Graphql API.

**Comment by resistorsoftware** [comment]
From early days I have gone through **three** or **four** use patterns, none of which satisfied me. This one seems pretty good. Easy to flesh out.
