### ISSUE TITLE
Just a Heads up!

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify_graphql#28]
A long time ago, I wrote my own way of dealing with GraphQL in Shopify. I decided I hated Graphql as a constant in the class name and module work, so I added an inflection, and lo-and-behold I passed Zeitwork and had GraphQL everywhere I wanted it. 

Then I loaded this library in parallel to test and develop with it, and never noticed much about how it uses _Graphql_ and has no inflection setting. I had removed my inflector to test and develop but forgot that when pushing to production where all of a sudden I had no Shopify::Graphql defined properly, due to the missing inflection. 

**So be careful** and if you play with inflections, be worried! Sometimes they can bit you on the old GraphQL versus Graphql settings!

**Comment by kirillplatonov** [comment]
Thanks for the heads up 👍
