### ISSUE TITLE
Shopify Access Scopes issue

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify_graphql#35]
I have an App with an API token that clearly offers up the **write_products** scope. Unfortunately when I try using Shopify to upload some Bulk Changes I get this:

ShopifyGraphql::ConnectionError: Failed. Response code = ACCESS_DENIED. Response message = Access denied for stagedUploadsCreate field.. Documentation = https://shopify.dev/api/usage/access-scopes.

Anyone else try and make GQL calls with correct access scopes that get rejected?

**Comment by kirillplatonov** [comment]
Please do not use Github Issues for generic development questions. It's better to ask them in Shopify Partner Slack or Discord. Let's keep issues on topic and focused on real bugs/problems in libraries.
