### ISSUE TITLE
Support Shopify Partner API

### ISSUE THREAD

**Issue by remy727** [kirillplatonov/shopify_graphql#36]
I know `shopify-api-ruby` gem doesn't support Shopify Partner API yet.
Does `shopify-api-ruby` gem need to support Partner API first to support it in this gem?

**Comment by kirillplatonov** [comment]
Right now we depend on `shopify_api` gem to make actual API requests, so yes. I have only one call to Partner API in my apps so I use `HTTParty.post` directly without any wrappers.
