### ISSUE TITLE
Rate limit extension?

### ISSUE THREAD

**Issue by hrdwdmrbl** [kirillplatonov/shopify_graphql#37]
I searched your code but I can't find anything related to the rate limits? I can't find anything in your code related to it.

I'd like to write a wrapper that automatically throttles the client's requests.

**Comment by kirillplatonov** [comment]
Added description of available rate limit methods:
https://github.com/kirillplatonov/shopify_graphql?tab=readme-ov-file#rate-limits

Is that what you're looking for?
