### ISSUE TITLE
Q: Custom App + Access Token

### ISSUE THREAD

**Issue by kbachl** [kirillplatonov/shopify_graphql#45]
Hi,

how can I use this gem if I only have the x-access token from a custom install like described here:
https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/generate-app-access-tokens-admin

The shopify_app expects an whole oAuth that I cant seem to get working in case of a single user custom app.

**Comment by kirillplatonov** [comment]
You'll need to create custom app for the store and then grab access token and API credentials from it. 
![CleanShot 2024-10-13 at 21 56 52@2x](https://github.com/user-attachments/assets/8f477a78-5b11-4320-9dc3-6b5ff207309a)

These credentials will be sufficient to set `api_key` and `secret` in ShopifyApp initializer. And then you can add the following method to Shop model:
```rb
class Shop < ActiveRecord::Base
  include ShopifyApp::ShopSessionStorageWithScopes

  def self.system
    new(
      shopify_domain: "MYSHOPIFY_DOMAIN",
      shopify_token: "API_ACCESS_TOKEN_FOR_CUSTOM_APP"
    )
  end
end
```

Using this method, you should be able to make API calls like this:
```rb
Shop.system.with_shopify_session do
  GetOrder.call(id: order.shopify_gid)
end
```

**Comment by kbachl** [comment]
Thank you for answering my Question. I made a worarkound by using a custom class:

```
class MyShop
  def self.with_session(&block)
    ShopifyAPI::Auth::Session.temp(shop: "xxx.myshopify.com",
                                   access_token: "xxxxx-token", &block)
  end
end
```

So I can use it that way:

```
MyShop.with_session do
  GetOrder.call(id: order.shopify_gid)
end
```

Is this any better or worse? Since I didnt even really install the shoppify_app gem after I couldnt get it to work in first case, but just pulled it in with your gem. 
Any comment is highly appreciated as I'd like to enhance the documentation as very many questions in the official forums seem to come from Auth with token isntead of o-Auth as you need token auth for *every* custom app that is not to be sold/ deployed.

**Comment by kirillplatonov** [comment]
Documented both approaches. Thanks for sharing!

There seems to be no way to authenticate custom apps via shopify_app gem. I end up spinning my own authentication with devise. However, shopify_app gem still might be helpful for handling webhooks, for example.
