### ISSUE TITLE
NameError: uninitialized constant ShopifyGraphql::CurrentShop

### ISSUE THREAD

**Issue by kmeister2000** [kirillplatonov/shopify_graphql#56]
I'm using this gem in the context of a brand new Shopify rails app based off the shopify_app gem (and @kirillplatonov 's hotwire rails app template)

I was experimenting with grabbing store details on installation to store in my db.

In attempting to use ShopifyGraphql::CurrentShop I get the error: `NameError: uninitialized constant ShopifyGraphql::CurrentShop`

I've experimented with several other classes from this gem and I do not get that error.

When inspecting the ShopifyGraphql namespace I see that the CurrentShop constant isn't defined, but the others are.
`pry> ShopifyGraphql.constants 
=> [:TooManyRequests,
 :ClientError,
 :ShopLocked,
 :PreconditionFailed,
 :VERSION,
 :DeletePrivateMetafield,
 :UserError,
 :UpsertPrivateMetafield,
 :CreateWebhooksJob,
 :DestroyWebhooksJob,
 :MethodNotAllowed,
 :Engine,
 :Client,
 :Mutation,
 :PayloadVerification,
 :Resource,
 :WebhooksManager,
 :UpdateWebhooksJob,
 :GetAppSubscription,
 :WebhookVerification,
 :RedactJobParams,
 :ConnectionError,
 :ServerError,
 :Webhook,
 :Shop,
 :GraphqlWebhooksController,
 :AppSubscriptionFields,
 :CancelSubscription,
 :CreateRecurringSubscription,
 :CreateUsageSubscription,
 :Response,
 :UnauthorizedAccess,
 :PaymentRequired,
 :ForbiddenAccess,
 :Query,
 :ResourceNotFound,
 :ResourceGone,
 :Configuration,
 :ResourceConflict,
 :BadRequest]`

I examined the source for the various "built-in" calls in this gem and I was unable to discern any different in implementation that might explain this. 

Can you suggest any further debugging tips or other info I might provide that could be helpful in tracking this down?

Thank you for the delightful gem, it's a big help.

**Comment by forsbergplustwo** [comment]
@kmeister2000 - You may have already checked, but are you sure you have the lastest version? I know `CurrentShop` is relatively new in this gem, so may simply require a `bundle update shopify_graphql`

**Comment by kmeister2000** [comment]
That did the trick.

I had generated the app from a template and made the assumption it was using the latest version - I didn't realize the shopify_graphql gem was pegged to an old branch (unified_exceptions / version 1.2.6)

After updating to the latest version it works as expected.

Thanks for pointing out my mistake.

**Comment by forsbergplustwo** [comment]
Fantastic, glad it was helpful! Only came to mind because I've made the same mistake a million times 😅
