### ISSUE TITLE
Setting a session, but not being recognized

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify_graphql#58]
As a favor I am trying to update a buddy using Rails 6, and no Shopify App to this GraphQL so he can continue making API calls for his business. Please excuse the oddity here then, as this use of the API and GQL is not conventional Shopify!! He is still using RestAPI calls from API version 9, and knows RestAPI is soon DOA, so I volunteered to phase him in to GraphQL.

Shopify API v 14.6 is available and seems to work fine, I upped to Ruby 3.4.1 and therefore, I think we're good to go.

Code like this works *perfect* in a rake task. But as soon as I try and use it in a plain jane background job worker, I get the response

`(irb):1:in '<main>': No passed or active session (ShopifyAPI::Errors::NoActiveSessionError)`

I see that I am passing the session to the API with an activate_session call, but this is apparently not good enough. What am I doing wrong here, such that a rake task works fine, but a plain jane GQL call fails on this session? Help? Please! 

```
      access_token = ENV["SHOPIFY_ACCESS_TOKEN"]
      shop_name = "#{ENV["SHOPIFY_SHOP_NAME"]}.myshopify.com"
      session = ShopifyAPI::Auth::Session.new(
        shop: shop_name,
        access_token: access_token
      )
      ShopifyAPI::Context.activate_session(session)
      order = GetOrder.call(id: "gid://shopify/Order/2263360897").data
```

**Comment by kirillplatonov** [comment]
It might be threads issue in `ShopifyAPI::Context.activate_session`. You better wrap API calls with temp session:
```rb
ShopifyAPI::Auth::Session.temp(shop: shop_name, access_token: access_token) do
  order = GetOrder.call(id: "gid://shopify/Order/2263360897").data
end
```

To make it clean and less verbose you can create `Shop.with_shopify_session` method:
```rb
# app/models/shop.rb
def Shop
  def self.with_shopify_session(&block)
    ShopifyAPI::Auth::Session.temp(
      shop: "MYSHOPIFY_DOMAIN",
      access_token: "API_ACCESS_TOKEN_FOR_CUSTOM_APP",
      &block
    )
  end
end
```

And use it like this:
```rb
Shop.with_shopify_session do
  order = GetOrder.call(id: "gid://shopify/Order/2263360897").data
end
```

Docs for custom apps is available in README: https://github.com/kirillplatonov/shopify_graphql?tab=readme-ov-file#custom-apps
